FROM node:18 AS build
WORKDIR /app
COPY formapp3.client/package*.json ./
RUN npm install
COPY formapp3.client/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]